export const hurufAsas = [
  {
    id: "HRF-ASAS-001",
    arabic: "مِنْ",
    meaning: "daripada",
    type: "huruf",
    level: "asas",
    lesson: "huruf",
    difficulty: 1,
    tags: ["jar"],
    audio: null,
    image: null,
  },
  {
    id: "HRF-ASAS-002",
    arabic: "إِلَى",
    meaning: "ke",
    type: "huruf",
    level: "asas",
    lesson: "huruf",
    difficulty: 1,
    tags: ["jar"],
    audio: null,
    image: null,
  },
  {
    id: "HRF-ASAS-003",
    arabic: "فِي",
    meaning: "di dalam",
    type: "huruf",
    level: "asas",
    lesson: "huruf",
    difficulty: 1,
    tags: ["jar"],
    audio: null,
    image: null,
  },
];