export const fiilAsas = [
  {
    id: "FIL-ASAS-001",
    arabic: "كَتَبَ",
    meaning: "telah menulis",
    type: "fiil",
    level: "asas",
    lesson: "fiil",
    difficulty: 1,
    tags: ["madhi"],
    audio: null,
    image: null,
  },
  {
    id: "FIL-ASAS-002",
    arabic: "ذَهَبَ",
    meaning: "telah pergi",
    type: "fiil",
    level: "asas",
    lesson: "fiil",
    difficulty: 1,
    tags: ["madhi"],
    audio: null,
    image: null,
  },
  {
    id: "FIL-ASAS-003",
    arabic: "جَلَسَ",
    meaning: "telah duduk",
    type: "fiil",
    level: "asas",
    lesson: "fiil",
    difficulty: 1,
    tags: ["madhi"],
    audio: null,
    image: null,
  },
];