export const isimAsas = [
  { id: "ISM-ASAS-001", arabic: "كِتَابٌ", meaning: "buku", type: "isim", lesson: "isim", level: "asas", difficulty: 1, tags: ["tanwin", "mufrad"], audio: null, image: null },
  { id: "ISM-ASAS-002", arabic: "قَلَمٌ", meaning: "pen", type: "isim", lesson: "isim", level: "asas", difficulty: 1, tags: ["tanwin", "mufrad"], audio: null, image: null },
  { id: "ISM-ASAS-003", arabic: "مَسْجِدٌ", meaning: "masjid", type: "isim", lesson: "isim", level: "asas", difficulty: 1, tags: ["tanwin", "mufrad"], audio: null, image: null },
  { id: "ISM-ASAS-004", arabic: "بَيْتٌ", meaning: "rumah", type: "isim", lesson: "isim", level: "asas", difficulty: 1, tags: ["tanwin", "mufrad"], audio: null, image: null },
  { id: "ISM-ASAS-005", arabic: "بَابٌ", meaning: "pintu", type: "isim", lesson: "isim", level: "asas", difficulty: 1, tags: ["tanwin", "mufrad"], audio: null, image: null },
  { id: "ISM-ASAS-006", arabic: "طَالِبٌ", meaning: "pelajar lelaki", type: "isim", lesson: "isim", level: "asas", difficulty: 1, tags: ["tanwin", "mufrad"], audio: null, image: null },
  { id: "ISM-ASAS-007", arabic: "مُعَلِّمٌ", meaning: "guru lelaki", type: "isim", lesson: "isim", level: "asas", difficulty: 1, tags: ["tanwin", "mufrad"], audio: null, image: null },
  { id: "ISM-ASAS-008", arabic: "مَدْرَسَةٌ", meaning: "sekolah", type: "isim", lesson: "isim", level: "asas", difficulty: 1, tags: ["tanwin", "mufrad"], audio: null, image: null },
  { id: "ISM-ASAS-009", arabic: "مَدِينَةٌ", meaning: "bandar", type: "isim", lesson: "isim", level: "asas", difficulty: 1, tags: ["tanwin", "mufrad"], audio: null, image: null },
  { id: "ISM-ASAS-010", arabic: "قَرْيَةٌ", meaning: "kampung", type: "isim", lesson: "isim", level: "asas", difficulty: 1, tags: ["tanwin", "mufrad"], audio: null, image: null },

  { id: "ISM-ASAS-011", arabic: "رَجُلٌ", meaning: "lelaki", type: "isim", lesson: "isim", level: "asas", difficulty: 1, tags: ["tanwin", "mufrad"], audio: null, image: null },
  { id: "ISM-ASAS-012", arabic: "وَلَدٌ", meaning: "budak lelaki", type: "isim", lesson: "isim", level: "asas", difficulty: 1, tags: ["tanwin", "mufrad"], audio: null, image: null },
  { id: "ISM-ASAS-013", arabic: "بِنْتٌ", meaning: "anak perempuan", type: "isim", lesson: "isim", level: "asas", difficulty: 1, tags: ["tanwin", "mufrad"], audio: null, image: null },
  { id: "ISM-ASAS-014", arabic: "أُمٌّ", meaning: "ibu", type: "isim", lesson: "isim", level: "asas", difficulty: 1, tags: ["tanwin", "mufrad"], audio: null, image: null },
  { id: "ISM-ASAS-015", arabic: "أَبٌ", meaning: "bapa", type: "isim", lesson: "isim", level: "asas", difficulty: 1, tags: ["tanwin", "mufrad"], audio: null, image: null },

  { id: "ISM-ASAS-016", arabic: "مَاءٌ", meaning: "air", type: "isim", lesson: "isim", level: "asas", difficulty: 1, tags: ["tanwin", "mufrad"], audio: null, image: null },
  { id: "ISM-ASAS-017", arabic: "طَعَامٌ", meaning: "makanan", type: "isim", lesson: "isim", level: "asas", difficulty: 1, tags: ["tanwin", "mufrad"], audio: null, image: null },
  { id: "ISM-ASAS-018", arabic: "لَبَنٌ", meaning: "susu", type: "isim", lesson: "isim", level: "asas", difficulty: 1, tags: ["tanwin", "mufrad"], audio: null, image: null },
  { id: "ISM-ASAS-019", arabic: "خُبْزٌ", meaning: "roti", type: "isim", lesson: "isim", level: "asas", difficulty: 1, tags: ["tanwin", "mufrad"], audio: null, image: null },
  { id: "ISM-ASAS-020", arabic: "تَمْرٌ", meaning: "kurma", type: "isim", lesson: "isim", level: "asas", difficulty: 1, tags: ["tanwin", "mufrad"], audio: null, image: null },

  { id: "ISM-ASAS-021", arabic: "شَمْسٌ", meaning: "matahari", type: "isim", lesson: "isim", level: "asas", difficulty: 1, tags: ["tanwin", "mufrad"], audio: null, image: null },
  { id: "ISM-ASAS-022", arabic: "قَمَرٌ", meaning: "bulan", type: "isim", lesson: "isim", level: "asas", difficulty: 1, tags: ["tanwin", "mufrad"], audio: null, image: null },
  { id: "ISM-ASAS-023", arabic: "نَجْمٌ", meaning: "bintang", type: "isim", lesson: "isim", level: "asas", difficulty: 1, tags: ["tanwin", "mufrad"], audio: null, image: null },
  { id: "ISM-ASAS-024", arabic: "سَمَاءٌ", meaning: "langit", type: "isim", lesson: "isim", level: "asas", difficulty: 1, tags: ["tanwin", "mufrad"], audio: null, image: null },
  { id: "ISM-ASAS-025", arabic: "أَرْضٌ", meaning: "bumi", type: "isim", lesson: "isim", level: "asas", difficulty: 1, tags: ["tanwin", "mufrad"], audio: null, image: null },

  { id: "ISM-ASAS-026", arabic: "حَدِيقَةٌ", meaning: "taman", type: "isim", lesson: "isim", level: "asas", difficulty: 1, tags: ["tanwin", "mufrad"], audio: null, image: null },
  { id: "ISM-ASAS-027", arabic: "شَجَرَةٌ", meaning: "pokok", type: "isim", lesson: "isim", level: "asas", difficulty: 1, tags: ["tanwin", "mufrad"], audio: null, image: null },
  { id: "ISM-ASAS-028", arabic: "زَهْرَةٌ", meaning: "bunga", type: "isim", lesson: "isim", level: "asas", difficulty: 1, tags: ["tanwin", "mufrad"], audio: null, image: null },
  { id: "ISM-ASAS-029", arabic: "نَهْرٌ", meaning: "sungai", type: "isim", lesson: "isim", level: "asas", difficulty: 1, tags: ["tanwin", "mufrad"], audio: null, image: null },
  { id: "ISM-ASAS-030", arabic: "جَبَلٌ", meaning: "gunung", type: "isim", lesson: "isim", level: "asas", difficulty: 1, tags: ["tanwin", "mufrad"], audio: null, image: null },

  { id: "ISM-ASAS-031", arabic: "كُرْسِيٌّ", meaning: "kerusi", type: "isim", lesson: "isim", level: "asas", difficulty: 1, tags: ["tanwin", "mufrad"], audio: null, image: null },
  { id: "ISM-ASAS-032", arabic: "مَكْتَبٌ", meaning: "meja", type: "isim", lesson: "isim", level: "asas", difficulty: 1, tags: ["tanwin", "mufrad"], audio: null, image: null },
  { id: "ISM-ASAS-033", arabic: "سَرِيرٌ", meaning: "katil", type: "isim", lesson: "isim", level: "asas", difficulty: 1, tags: ["tanwin", "mufrad"], audio: null, image: null },
  { id: "ISM-ASAS-034", arabic: "مِفْتَاحٌ", meaning: "kunci", type: "isim", lesson: "isim", level: "asas", difficulty: 1, tags: ["tanwin", "mufrad"], audio: null, image: null },
  { id: "ISM-ASAS-035", arabic: "سَيَّارَةٌ", meaning: "kereta", type: "isim", lesson: "isim", level: "asas", difficulty: 1, tags: ["tanwin", "mufrad"], audio: null, image: null },

  { id: "ISM-ASAS-036", arabic: "يَوْمٌ", meaning: "hari", type: "isim", lesson: "isim", level: "asas", difficulty: 1, tags: ["tanwin", "mufrad"], audio: null, image: null },
  { id: "ISM-ASAS-037", arabic: "لَيْلٌ", meaning: "malam", type: "isim", lesson: "isim", level: "asas", difficulty: 1, tags: ["tanwin", "mufrad"], audio: null, image: null },
  { id: "ISM-ASAS-038", arabic: "صَبَاحٌ", meaning: "pagi", type: "isim", lesson: "isim", level: "asas", difficulty: 1, tags: ["tanwin", "mufrad"], audio: null, image: null },
  { id: "ISM-ASAS-039", arabic: "مَسَاءٌ", meaning: "petang", type: "isim", lesson: "isim", level: "asas", difficulty: 1, tags: ["tanwin", "mufrad"], audio: null, image: null },
  { id: "ISM-ASAS-040", arabic: "وَقْتٌ", meaning: "masa", type: "isim", lesson: "isim", level: "asas", difficulty: 1, tags: ["tanwin", "mufrad"], audio: null, image: null },

  { id: "ISM-ASAS-041", arabic: "صَدِيقٌ", meaning: "sahabat", type: "isim", lesson: "isim", level: "asas", difficulty: 1, tags: ["tanwin", "mufrad"], audio: null, image: null },
  { id: "ISM-ASAS-042", arabic: "ضَيْفٌ", meaning: "tetamu", type: "isim", lesson: "isim", level: "asas", difficulty: 1, tags: ["tanwin", "mufrad"], audio: null, image: null },
  { id: "ISM-ASAS-043", arabic: "إِمَامٌ", meaning: "imam", type: "isim", lesson: "isim", level: "asas", difficulty: 1, tags: ["tanwin", "mufrad"], audio: null, image: null },
  { id: "ISM-ASAS-044", arabic: "مُؤْمِنٌ", meaning: "orang beriman", type: "isim", lesson: "isim", level: "asas", difficulty: 1, tags: ["tanwin", "mufrad"], audio: null, image: null },
  { id: "ISM-ASAS-045", arabic: "مُسْلِمٌ", meaning: "orang Islam", type: "isim", lesson: "isim", level: "asas", difficulty: 1, tags: ["tanwin", "mufrad"], audio: null, image: null },

  { id: "ISM-ASAS-046", arabic: "قَوْمٌ", meaning: "kaum", type: "isim", lesson: "isim", level: "asas", difficulty: 1, tags: ["tanwin", "mufrad"], audio: null, image: null },
  { id: "ISM-ASAS-047", arabic: "جَيْشٌ", meaning: "tentera", type: "isim", lesson: "isim", level: "asas", difficulty: 1, tags: ["tanwin", "mufrad"], audio: null, image: null },
  { id: "ISM-ASAS-048", arabic: "سُوقٌ", meaning: "pasar", type: "isim", lesson: "isim", level: "asas", difficulty: 1, tags: ["tanwin", "mufrad"], audio: null, image: null },
  { id: "ISM-ASAS-049", arabic: "دَرْسٌ", meaning: "pelajaran", type: "isim", lesson: "isim", level: "asas", difficulty: 1, tags: ["tanwin", "mufrad"], audio: null, image: null },
  { id: "ISM-ASAS-050", arabic: "سُؤَالٌ", meaning: "soalan", type: "isim", lesson: "isim", level: "asas", difficulty: 1, tags: ["tanwin", "mufrad"], audio: null, image: null },
];